import streamlit
streamlit.title('My Parents New Healthy Diner')
streamlit.header('Breakfast Menu')
streamlit.subheader('Classic English Breakfast')
streamlit.text('🍞Contains bread,french fries,baked beans,scrambled eggs. Options: Chicken, Ham, Pork')
streamlit.subheader('Good Morning Life :-)')
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('🥑Kale, Spinach & Rocket Smoothie')
streamlit.text('🐔Hard-Boiled Free-Range Egg')
streamlit.header('Lunch Menu')
streamlit.subheader('🥗Continental Bonanza!')
streamlit.text(' Contains Soup, choice of non veg, rice/bread Options: Chicken, fish, beef')
streamlit.header('Dinner Menu')
streamlit.subheader('Light and funnnn')
streamlit.text(' Options: 🥣Soup, Thai noodles, pasta, Chicken rice')
streamlit.header('Build Your Own Fruit Smoothie 🥝🍇')

